project:
  title: "hw5"

number-sections: true
toc: true

bibliography: references.bib
csl: ieee.csl
reference-section-title: "Literatura"

format:
  html:
    code-fold: true
    css: styles.css
    embed-resources: true

knitr:
  opts_chunk:
    echo: true
    eval: true
    message: false
    warning: false
